import { G, GOLD, BLUE, PURPLE } from "../../../lib/tokens";

export interface ServiceItem {
  slug: string;
  title: string;
  tagline: string;
  color: string;
  pill: string;
  heroDesc: string;
  stats: { value: string; label: string }[];
  offerings: { title: string; desc: string }[];
  process: { step: string; title: string; desc: string }[];
  why: { title: string; desc: string }[];
  industries?: string[];
  range?: string;
}

export const SERVICES_DATA: Record<string, ServiceItem> = {
  "investment-banking": {
    slug: "investment-banking", title: "Investment Banking", pill: "Capital Markets",
    color: G, range: "₹10 Cr – ₹2,000 Cr+",
    tagline: "Full-Spectrum Capital Solutions for India's Growth Sectors.",
    heroDesc: "From senior secured debt to mezzanine and equity — OMNI Fincon's Investment Banking vertical structures bespoke capital solutions for promoters, corporates, and institutional clients across 30+ sectors.",
    stats: [
      { value: "₹20,000 Cr+", label: "Structured Financing"   },
      { value: "1,000+",     label: "Projects Executed"      },
      { value: "45 Days",    label: "Avg. Mandate-to-Close"  },
      { value: "30+",        label: "Sectors Served"         },
    ],
    offerings: [
      { title: "Fund Raising — Debt & Equity", desc: "Structured fundraising from PSU banks, private lenders, NBFCs, HNIs, and institutional equity investors across all ticket sizes." },
      { title: "HNI & Family Office Funding",  desc: "Direct placement with India's high-net-worth and ultra-HNI family offices for real estate, renewable energy, and growth capital needs." },
      { title: "M&A Advisory",                 desc: "Buy-side and sell-side M&A advisory including valuation, deal structuring, due diligence coordination, and negotiation." },
      { title: "Corporate Finance Advisory",   desc: "Balance sheet optimisation, working capital restructuring, credit rating advisory, and treasury management solutions." },
      { title: "Project Finance",              desc: "Structured project finance for infrastructure, power, hospitality, and industrial projects — including DSCR modelling and lender coordination." },
      { title: "Structured Finance",           desc: "Complex financing structures including NCD issuance, securitisation, asset-backed lending, and off-balance sheet arrangements." },
      { title: "Bridge Financing",             desc: "Short-term bridge capital for land acquisition, project kick-off, and transitional funding needs at competitive rates." },
      { title: "SME / MSME Solutions",         desc: "Tailored capital access programs for small and medium enterprises including CGTMSE-backed loans and cluster financing." },
    ],
    process: [
      { step: "01", title: "Initial Mandate Discussion", desc: "Understand business requirements, capital structure goals, and project timeline in a confidential consultation." },
      { step: "02", title: "Information Memorandum",     desc: "Prepare detailed IM with financial models, sector analysis, promoter credentials, and deal thesis." },
      { step: "03", title: "Lender / Investor Outreach", desc: "Leverage our network of 50+ banks, NBFCs, and institutional investors for targeted mandate distribution." },
      { step: "04", title: "Term Sheet Negotiation",     desc: "Review and negotiate LOIs, term sheets, and sanction letters to secure optimal terms for the client." },
      { step: "05", title: "Due Diligence & Closure",   desc: "Coordinate legal, financial, and technical due diligence through to financial close and disbursement." },
    ],
    why: [
      { title: "Deep Lender Network",       desc: "50+ relationships with PSU banks, private banks, NBFCs, and institutional investors built over 15+ years." },
      { title: "Sector Expertise",          desc: "Dedicated vertical teams for Real Estate, Energy, Healthcare, NBFC, and Industrial financing." },
      { title: "Speed to Market",           desc: "Average 45-day mandate-to-close timeline through pre-screened lender relationships and streamlined documentation." },
      { title: "Conflict-Free Advisory",    desc: "We represent the client's interests exclusively, with no lender-side incentives distorting our advice." },
    ],
    industries: ["Real Estate","Renewable Energy","Healthcare","Hospitality","Infrastructure","NBFC","Steel","Pharmaceutical","Logistics","Education"],
  },

  "wealth-advisory": {
    slug: "wealth-advisory", title: "Wealth & Risk Advisory", pill: "Wealth Management",
    color: BLUE, range: "₹50 L – ₹500 Cr+",
    tagline: "Comprehensive Wealth Management for HNIs, Family Offices & Corporates.",
    heroDesc: "OMNI Fincon's Wealth & Risk Advisory practice delivers bespoke portfolio construction, estate planning, insurance advisory, and risk-optimised investment strategies for India's discerning investors.",
    stats: [
      { value: "₹2,400 Cr+", label: "Assets Under Advisory" },
      { value: "18%+",        label: "Avg. Portfolio Alpha"   },
      { value: "500+",        label: "HNI & Family Clients"   },
      { value: "12+",         label: "Asset Classes Covered"  },
    ],
    offerings: [
      { title: "Portfolio Construction & Management", desc: "Asset allocation across equities, fixed income, alternatives, and real assets optimised for risk-adjusted returns." },
      { title: "Insurance Advisory",                  desc: "Comprehensive life, health, key-man, and liability insurance structuring for individuals and corporates." },
      { title: "Estate & Succession Planning",        desc: "Trust structuring, will drafting coordination, and generational wealth transfer advisory." },
      { title: "Alternative Investments",             desc: "Access to AIFs, unlisted equities, pre-IPO opportunities, and structured products for qualified investors." },
      { title: "Tax-Efficient Structuring",           desc: "Investment structuring through HUFs, family trusts, and holding companies for optimal tax outcomes." },
      { title: "Risk Management",                     desc: "Comprehensive risk profiling, portfolio stress testing, and hedging strategies using derivatives and insurance." },
      { title: "NRI Wealth Advisory",                 desc: "Specialised advisory for non-resident Indians covering FEMA compliance, repatriation, and India-centric investments." },
      { title: "Corporate Surplus Management",        desc: "Efficient deployment of corporate treasury surpluses in short-duration instruments and liquid strategies." },
    ],
    process: [
      { step: "01", title: "Wealth Discovery Session",     desc: "Deep-dive financial assessment covering goals, risk tolerance, existing assets, and future liquidity needs." },
      { step: "02", title: "Investment Policy Statement",   desc: "Define clear investment objectives, constraints, benchmarks, and guidelines in a formal IPS." },
      { step: "03", title: "Portfolio Blueprint",           desc: "Construct customised asset allocation with specific product recommendations across all asset classes." },
      { step: "04", title: "Implementation & Onboarding",  desc: "Seamless account opening, fund transfers, and systematic portfolio deployment." },
      { step: "05", title: "Quarterly Reviews & Rebalance", desc: "Regular performance reviews with rebalancing recommendations and updated tax-loss harvesting strategies." },
    ],
    why: [
      { title: "Open Architecture",         desc: "We recommend the best products across 50+ fund houses, insurance providers, and alternative platforms — no proprietary bias." },
      { title: "Holistic Planning",         desc: "Integration of investment, insurance, tax, and estate planning for true 360° wealth management." },
      { title: "Research-Driven Approach",  desc: "In-house macro research and fund analysis team providing independent views on markets and instruments." },
      { title: "Dedicated Relationship Manager", desc: "Single point of contact for all wealth needs available 24/7 for our premium clients." },
    ],
    industries: ["HNI Individuals","Ultra-HNI Family Offices","Corporate Promoters","NRI Investors","Institutional Investors"],
  },

  "real-estate-advisory": {
    slug: "real-estate-advisory", title: "Land & Real Estate Advisory", pill: "Real Estate",
    color: GOLD, range: "₹25 Cr – ₹500 Cr+",
    tagline: "Expert Land, JV, and Asset Advisory for India's Real Estate Sector.",
    heroDesc: "OMNI Fincon's Real Estate Advisory practice provides comprehensive guidance on land acquisition, joint venture structuring, title due diligence, and asset monetisation for developers, investors, and corporates.",
    stats: [
      { value: "₹3,200 Cr+", label: "Real Estate Mandates"       },
      { value: "120+",        label: "Land & JV Transactions"     },
      { value: "45 Days",     label: "Avg. Transaction Closure"   },
      { value: "10+",         label: "Cities Covered Across India" },
    ],
    offerings: [
      { title: "Land Acquisition Advisory",   desc: "End-to-end advisory on land sourcing, pricing, due diligence, regulatory clearances, and structured acquisition." },
      { title: "JV Structuring & Advisory",   desc: "Design of revenue share, profit share, and hybrid JV structures between landowners, developers, and investors." },
      { title: "Title Due Diligence",         desc: "Coordination of legal title searches, encumbrance clearances, and litigation risk assessment." },
      { title: "Asset Monetisation",          desc: "Sale-leaseback, rent securitisation, and structured exits for commercial and income-yielding real estate assets." },
      { title: "Real Estate Fund Raising",    desc: "Debt and equity capital raising for residential, commercial, warehousing, and hospitality projects." },
      { title: "RERA Advisory",               desc: "Project registration, compliance structuring, and escrow management under RERA regulations." },
      { title: "Valuation & Feasibility",     desc: "Independent valuation opinions, project feasibility studies, and market analysis for developers and lenders." },
      { title: "Lease Rental Discounting",    desc: "LRD financing structures against committed lease rentals from AA-rated corporate tenants." },
    ],
    process: [
      { step: "01", title: "Site & Project Assessment", desc: "Evaluate land parcels or project assets against market benchmarks, approvals, and development potential." },
      { step: "02", title: "Structuring Advisory",      desc: "Design optimal deal structure — JV, SPA, DA, or hybrid — aligned with all parties' financial objectives." },
      { step: "03", title: "Capital Solution Design",   desc: "Structure debt, equity, or mezzanine financing as required, mapping to the project's cash flow profile." },
      { step: "04", title: "Lender / Partner Introduction", desc: "Connect developer and landowner with the right financing or development partners from our curated network." },
      { step: "05", title: "Documentation & Closure",   desc: "Coordinate legal drafting, stamp duty, and registration through to financial close and disbursement." },
    ],
    why: [
      { title: "Pan-India Market Intelligence", desc: "Ground-level market data across 10+ cities including tier-2 markets covering residential, commercial, and industrial segments." },
      { title: "Developer & Investor Network", desc: "Pre-qualified network of real estate developers, institutional funds, and family office investors." },
      { title: "Legal Coordination Expertise", desc: "Relationships with top-tier real estate law firms ensuring watertight title and documentation." },
      { title: "Full-Cycle Support",           desc: "From land identification through project completion, OMNI Fincon provides continuity across the real estate lifecycle." },
    ],
    industries: ["Residential Development","Commercial Real Estate","Industrial & Warehousing","Hospitality & Hotels","Mixed-Use Township","Retail & Mall Projects"],
  },

  "retail-banking": {
    slug: "retail-banking", title: "Retail Banking & Credit", pill: "Banking & Loans",
    color: PURPLE, range: "₹5 L – ₹50 Cr",
    tagline: "Smart Credit Solutions for Individuals & Businesses Across India.",
    heroDesc: "OMNI Fincon's Retail Banking vertical simplifies access to the right loan product at the best terms — from personal and home loans to complex business credit structuring for SMEs and corporates.",
    stats: [
      { value: "₹800 Cr+", label: "Loan Disbursements Facilitated" },
      { value: "5,000+",    label: "Loan Cases Processed"           },
      { value: "48 Hrs",    label: "Average Approval Timeline"      },
      { value: "50+",       label: "Lending Partners"               },
    ],
    offerings: [
      { title: "Personal Loan",           desc: "Unsecured personal loans up to ₹50L with competitive rates and minimal documentation." },
      { title: "Business Loan",           desc: "Collateral-free and secured business loans for working capital, expansion, and equipment purchase." },
      { title: "Home Loan",               desc: "End-to-end home loan advisory including balance transfer optimisation and top-up structuring." },
      { title: "Loan Against Property",   desc: "Structured LAP solutions leveraging residential, commercial, and industrial property assets." },
      { title: "Working Capital Loan",    desc: "CC/OD facilities, invoice discounting, and supply chain financing for operational cash needs." },
      { title: "Mortgage Loan",           desc: "Comprehensive mortgage loan structuring with optimal tenor, rate, and prepayment flexibility." },
      { title: "Education Loan",          desc: "Domestic and abroad study education loans with moratorium structuring and competitive pricing." },
      { title: "Credit Structuring",      desc: "Multi-bank credit facility structuring for businesses with complex banking relationship needs." },
    ],
    process: [
      { step: "01", title: "Loan Requirement Assessment", desc: "Understand loan purpose, quantum, repayment capacity, and existing credit obligations." },
      { step: "02", title: "Credit Profiling",            desc: "Detailed CIBIL/CRIF analysis, income assessment, and obligation-to-income ratio calculation." },
      { step: "03", title: "Product & Lender Matching",   desc: "Match requirement to optimal product from 50+ lenders ensuring best rate and terms." },
      { step: "04", title: "Application & Documentation", desc: "Prepare complete application file with all required documents for swift lender processing." },
      { step: "05", title: "Sanction & Disbursement",     desc: "Track and coordinate lender processing through sanction to disbursement in shortest time." },
    ],
    why: [
      { title: "50+ Lending Partners",   desc: "Access to the widest range of banks, NBFCs, and HFCs ensuring the best rate for your profile." },
      { title: "Paperless Processing",   desc: "Digital-first application journey with minimal physical documentation for faster turnaround." },
      { title: "No Hidden Charges",      desc: "Transparent fee structure with full disclosure of all costs before application submission." },
      { title: "Post-Disbursement Support", desc: "Continued support for partial prepayments, balance transfers, and top-up loans." },
    ],
    industries: ["Salaried Individuals","Self-Employed Professionals","SME Business Owners","Home Buyers","Students"],
  },

  "fund-raising": {
    slug: "fund-raising", title: "Fund Raising Advisory", pill: "Capital Markets",
    color: G, range: "₹10 Cr – ₹2,000 Cr+",
    tagline: "Strategic Capital Mobilisation Across Debt, Equity, and Hybrid Instruments.",
    heroDesc: "OMNI Fincon provides end-to-end fund raising advisory — from preparation of investment memorandums to lender relationship management and financial close — for promoters, developers, and corporates across India.",
    stats: [
      { value: "₹20,000 Cr+", label: "Capital Structured"      },
      { value: "1,000+",     label: "Projects Executed"       },
      { value: "50+",         label: "Lender Relationships"    },
      { value: "30 Days",     label: "Avg. First Term Sheet"   },
    ],
    offerings: [
      { title: "Debt Capital Raising",     desc: "Term loans, working capital facilities, and structured debt from banks, NBFCs, and debt funds." },
      { title: "Equity Capital Raising",   desc: "Private equity, venture capital, family office, and strategic investor placements." },
      { title: "Mezzanine Financing",      desc: "Hybrid debt-equity structures including compulsorily convertible instruments and OCPS." },
      { title: "NCD / Debenture Issuance", desc: "Privately placed NCD programs with institutional investors and family offices." },
      { title: "HNI Syndication",          desc: "Direct placement with high-net-worth individuals and informal investor networks." },
      { title: "AIF & PMS Funding",        desc: "Capital mobilisation from SEBI-registered Alternative Investment Funds and Portfolio Management Services." },
      { title: "International Capital",    desc: "Advisory on ECB, FVCI, and FDI routes for foreign capital into India." },
      { title: "NBFC / Co-lending",        desc: "Structured co-lending programs and priority sector credit linkages." },
    ],
    process: [
      { step: "01", title: "Business Understanding",       desc: "Deep-dive into the company's financials, project plans, promoter background, and capital requirements." },
      { step: "02", title: "Deal Structuring",             desc: "Define optimal instrument type, security package, covenants, and repayment structure." },
      { step: "03", title: "Information Memorandum",       desc: "Prepare investor-ready IM including financial projections, sector analysis, and deal thesis." },
      { step: "04", title: "Targeted Capital Outreach",    desc: "Approach curated list of relevant lenders/investors with confidential IM." },
      { step: "05", title: "Term Sheet to Financial Close", desc: "Negotiate terms, coordinate due diligence, and execute through to disbursement." },
    ],
    why: [
      { title: "Largest Lender Network",  desc: "50+ banks, NBFCs, and alternative lenders pre-qualified across all major ticket sizes and sectors." },
      { title: "Outcome-Oriented Fees",   desc: "Success-based fee model ensuring full alignment with the client's capital raise objectives." },
      { title: "Sector Specialists",      desc: "Dedicated teams for Real Estate, Infrastructure, Healthcare, and Manufacturing fund raises." },
      { title: "Post-Raise Support",      desc: "Ongoing lender liaison, covenant monitoring, and refinancing advisory post-closure." },
    ],
    industries: ["Real Estate","Infrastructure","Healthcare","Hospitality","Manufacturing","Renewable Energy","NBFC","Technology"],
  },

  "debt-syndication": {
    slug: "debt-syndication", title: "Debt Syndication", pill: "Capital Markets",
    color: BLUE, range: "₹25 Cr – ₹1,000 Cr+",
    tagline: "Structuring & Syndicating Debt Capital Across India's Banking System.",
    heroDesc: "OMNI Fincon's Debt Syndication practice structures and places senior, subordinated, and structured debt with the right combination of lenders for optimal pricing, tenor, and covenant flexibility.",
    stats: [
      { value: "₹3,500 Cr+", label: "Debt Syndicated"          },
      { value: "150+",        label: "Syndication Mandates"     },
      { value: "35+",         label: "Banking Relationships"    },
      { value: "60 Days",     label: "Avg. Syndication Timeline" },
    ],
    offerings: [
      { title: "Consortium Debt Arrangement",   desc: "Multi-bank consortium arrangement for large ticket mandates requiring diversified lender participation." },
      { title: "Club Deal Syndication",         desc: "Bilateral or small-club debt placements with 2-4 lenders for speed and relationship control." },
      { title: "NBFC Debt Placement",           desc: "Structured placement of debt instruments with leading NBFCs and HFCs." },
      { title: "Construction Finance",          desc: "Real estate construction finance syndication with disbursement-linked structures." },
      { title: "Corporate Term Loan",           desc: "Long-term corporate credit facilities for capex, acquisitions, and refinancing." },
      { title: "Rupee Bond Placement",          desc: "Private placement of corporate bonds with insurance companies, provident funds, and mutual funds." },
      { title: "Priority Sector Lending",       desc: "PSL-linked credit products for agriculture, housing, and MSME sectors." },
      { title: "Refinancing & Repricing",       desc: "Existing debt refinancing advisory for interest rate reduction and tenor extension." },
    ],
    process: [
      { step: "01", title: "Credit Appraisal Review",       desc: "Detailed analysis of the company/project financials, security coverage, and credit risk parameters." },
      { step: "02", title: "Syndication Structure Design",  desc: "Define lead arranger, participating lenders, tranching, and inter-creditor arrangements." },
      { step: "03", title: "Mandate Letter & Pitch",        desc: "Prepare detailed credit note and pitch to target lenders based on appetite and sector knowledge." },
      { step: "04", title: "Due Diligence Coordination",    desc: "Manage concurrent due diligence across multiple lenders to ensure aligned timelines." },
      { step: "05", title: "Documentation & Financial Close", desc: "Coordinate facility agreement, security creation, and first disbursement." },
    ],
    why: [
      { title: "Multi-Lender Expertise",   desc: "Deep experience managing complex consortium arrangements with up to 12 lenders." },
      { title: "Optimal Pricing",          desc: "Competitive bidding process ensuring clients receive market-leading interest rates." },
      { title: "Speed of Execution",       desc: "Pre-established relationships enable faster credit decisions and reduced documentation cycles." },
      { title: "Post-Syndication Support", desc: "Ongoing lender management, covenant compliance, and annual review support." },
    ],
    industries: ["Real Estate","Power & Energy","Infrastructure","Manufacturing","Healthcare","Hospitality"],
  },

  "ma-advisory": {
    slug: "ma-advisory", title: "M&A Advisory", pill: "Corporate Finance",
    color: GOLD, range: "₹50 Cr – ₹2,000 Cr+",
    tagline: "Strategic M&A Advisory for Transformative Business Transactions.",
    heroDesc: "OMNI Fincon's M&A Advisory practice advises promoters, corporates, and investors on buy-side and sell-side transactions — delivering independent valuation, deal structuring, and transaction management.",
    stats: [
      { value: "₹1,200 Cr+", label: "M&A Transactions Advised" },
      { value: "40+",         label: "Successful M&A Closures"  },
      { value: "90 Days",     label: "Avg. Transaction Timeline" },
      { value: "15+",         label: "Sectors Covered"           },
    ],
    offerings: [
      { title: "Buy-Side Advisory",        desc: "Target identification, approach, valuation, due diligence coordination, and acquisition structuring." },
      { title: "Sell-Side Advisory",       desc: "Business preparation, buyer outreach, competitive auction management, and deal closure." },
      { title: "Valuation Services",       desc: "Independent business valuations using DCF, comparable company, and precedent transaction approaches." },
      { title: "Deal Structuring",         desc: "Share purchase, asset purchase, slump sale, and demerger structures optimised for tax and regulatory efficiency." },
      { title: "Due Diligence Management", desc: "Coordination of financial, legal, technical, and commercial due diligence workstreams." },
      { title: "Post-Merger Integration",  desc: "Integration planning advisory covering organisational, system, and process consolidation." },
      { title: "Distressed M&A",           desc: "Advisory on acquisition of stressed/NPA assets through IBC and out-of-court resolution." },
      { title: "Cross-Border M&A",         desc: "India-outbound and inbound M&A advisory including FEMA, tax treaty, and regulatory clearances." },
    ],
    process: [
      { step: "01", title: "Mandate Definition",        desc: "Define acquisition/divestiture objectives, deal parameters, and success criteria." },
      { step: "02", title: "Target / Buyer Universe",   desc: "Identify and qualify strategic targets or prospective buyers aligned with client objectives." },
      { step: "03", title: "Valuation & Deal Terms",    desc: "Prepare valuation analysis and develop negotiating strategy for optimal deal terms." },
      { step: "04", title: "Due Diligence & LOI",       desc: "Coordinate due diligence workstreams and negotiate letter of intent / term sheet." },
      { step: "05", title: "Definitive Documentation",  desc: "Support legal counsel in SPA/SHA drafting, regulatory filings, and condition precedent fulfilment." },
    ],
    why: [
      { title: "Confidential & Discreet",  desc: "Strict NDAs and information barriers maintained throughout the transaction process." },
      { title: "Neutral Intermediary",     desc: "We represent one side exclusively, ensuring single-minded focus on client value maximisation." },
      { title: "Tax-Optimal Structuring",  desc: "Collaboration with Big-4 tax advisors to ensure the most efficient transaction structure." },
      { title: "Regulatory Navigation",    desc: "Deep knowledge of CCI, SEBI, FEMA, and sector-specific regulatory requirements." },
    ],
    industries: ["Manufacturing","Healthcare","Real Estate","Financial Services","Consumer & Retail","Technology","Logistics","Hospitality"],
  },

  "project-finance": {
    slug: "project-finance", title: "Project Finance", pill: "Capital Markets",
    color: G, range: "₹50 Cr – ₹5,000 Cr+",
    tagline: "Structuring Long-Term Capital for India's Infrastructure & Industrial Projects.",
    heroDesc: "OMNI Fincon structures project finance solutions for large infrastructure, industrial, and energy projects — leveraging SPV structures, government guarantees, and multi-lender arrangements for optimal capital deployment.",
    stats: [
      { value: "₹2,800 Cr+", label: "Project Finance Arranged" },
      { value: "60+",         label: "Projects Financed"        },
      { value: "25+",         label: "Years Average Project Life" },
      { value: "15+",         label: "Infrastructure Sub-Sectors" },
    ],
    offerings: [
      { title: "SPV/Project Structure Design",  desc: "Design of special purpose vehicle structures with appropriate equity-debt ratios and ring-fenced security." },
      { title: "DSCR Modelling",               desc: "Comprehensive financial modelling with DSCR-based debt sizing, sensitivity analysis, and lender-ready projections." },
      { title: "Lender Consortium Arrangement", desc: "Syndication across PSU banks, infrastructure lenders (PFC, REC, IREDA), and institutional debt funds." },
      { title: "Government Guarantee Advisory", desc: "Support in securing state and central government guarantees, VGF, and grants for eligible projects." },
      { title: "EPC Contract Review",           desc: "Risk allocation review of EPC, O&M, and off-take agreements in coordination with technical advisors." },
      { title: "Environmental Compliance",      desc: "Financing structures aligned with ESG and environmental impact assessment requirements." },
      { title: "Refinancing Solutions",         desc: "Long-term refinancing of construction-phase debt with optimised repayment structures." },
      { title: "Green Finance",                 desc: "Access to green bonds, sustainability-linked loans, and climate finance for eligible projects." },
    ],
    process: [
      { step: "01", title: "Project Viability Assessment",  desc: "Technical, commercial, and regulatory viability assessment of the proposed project." },
      { step: "02", title: "Financial Model Development",   desc: "Build banker-ready financial model with revenue forecasts, DSCR projections, and sensitivity tables." },
      { step: "03", title: "Capital Structure Optimisation", desc: "Define equity, senior debt, sub-debt, and grant funding mix for maximum IRR." },
      { step: "04", title: "Lender Coordination",           desc: "Simultaneous approach to multiple infrastructure lenders with tailored credit notes." },
      { step: "05", title: "Financial Closure",             desc: "Manage documentation, security creation, and conditions precedent through to first disbursement." },
    ],
    why: [
      { title: "Infrastructure Specialists",  desc: "Dedicated infrastructure finance team with deep sector knowledge across power, roads, ports, and hospitality." },
      { title: "Government Relationships",    desc: "Strong relationships with NITI Aayog, DFIs, and state nodal agencies for government-backed projects." },
      { title: "ESG & Green Finance",         desc: "Pioneering access to green finance instruments and ESG-compliant funding for sustainable projects." },
      { title: "End-to-End Support",          desc: "From concept through operation, OMNI's project finance team remains engaged across the project lifecycle." },
    ],
    industries: ["Solar & Wind Energy","Roads & Highways","Ports & Logistics","Healthcare Infrastructure","Education","Smart Cities","Water & Sanitation","Affordable Housing"],
  },

  "structured-finance": {
    slug: "structured-finance", title: "Structured Finance", pill: "Capital Markets",
    color: PURPLE, range: "₹25 Cr – ₹500 Cr+",
    tagline: "Complex, Off-Balance Sheet & Innovative Financing Structures.",
    heroDesc: "OMNI Fincon designs structured finance solutions that go beyond conventional lending — including NCDs, securitisation, asset-backed transactions, and off-balance sheet arrangements tailored to each client's unique situation.",
    stats: [
      { value: "₹800 Cr+", label: "Structured Deals Arranged" },
      { value: "50+",       label: "Innovative Structures"    },
      { value: "18+",       label: "Instrument Types Used"    },
      { value: "30+",       label: "Institutional Investors"  },
    ],
    offerings: [
      { title: "NCD / Bond Issuance",           desc: "Privately placed non-convertible debentures with institutional, HNI, and family office investors." },
      { title: "Securitisation",                desc: "Pool securitisation of loan receivables, lease rentals, and future cash flows for liquidity." },
      { title: "Asset-Backed Lending",          desc: "Structured financing backed by financial assets including securities, receivables, and royalties." },
      { title: "Off-Balance Sheet Arrangements", desc: "SPV-based transactions to optimise leverage ratios and regulatory capital treatment." },
      { title: "Compulsorily Convertible Instruments", desc: "Hybrid instruments combining debt coupons with equity conversion rights for investor flexibility." },
      { title: "Lease Rental Discounting",      desc: "Structured LRD against committed rentals from blue-chip corporate tenants." },
      { title: "Revenue-Based Financing",       desc: "Non-dilutive growth capital linked to future revenue streams for high-growth businesses." },
      { title: "Warehouse Financing",           desc: "Inventory and commodity financing for traders, manufacturers, and agri-processors." },
    ],
    process: [
      { step: "01", title: "Structural Assessment",        desc: "Analyse client's balance sheet, cash flows, and asset base to identify optimal structuring opportunity." },
      { step: "02", title: "Instrument Design",            desc: "Define key instrument parameters — tenor, coupon, security, conversion, and call/put options." },
      { step: "03", title: "Investor / Lender Mapping",    desc: "Match structure to the risk/return appetite of target institutional investors and lenders." },
      { step: "04", title: "Documentation & Rating",       desc: "Coordinate transaction documentation, credit rating (if applicable), and investor presentations." },
      { step: "05", title: "Execution & Settlement",       desc: "Execute instrument issuance or transaction closing with full compliance and regulatory filings." },
    ],
    why: [
      { title: "Creative Problem Solving",    desc: "Structured finance thinking applied to situations where conventional loans don't fit." },
      { title: "Regulatory Expertise",        desc: "Deep knowledge of SEBI, RBI, IRDA, and Companies Act requirements for structured instruments." },
      { title: "Investor Access",             desc: "Pre-qualified access to insurance companies, provident funds, and sophisticated HNI investors." },
      { title: "Cost Efficiency",             desc: "Structured instruments often achieve lower all-in cost than conventional bank finance for strong credit profiles." },
    ],
    industries: ["Real Estate","NBFCs","MFIs","Renewable Energy","Manufacturing","Consumer Finance","Retail","Healthcare"],
  },

  "nbfc-aif-launch": {
    slug: "nbfc-aif-launch", title: "NBFC / AIF Launch Advisory", pill: "Regulatory",
    color: BLUE, range: "Advisory Fee Based",
    tagline: "End-to-End Advisory for NBFC & AIF Registration in India.",
    heroDesc: "OMNI Fincon guides entrepreneurs, family offices, and institutional sponsors through the complete process of establishing NBFCs and SEBI-registered Alternative Investment Funds in India's evolving regulatory framework.",
    stats: [
      { value: "25+",   label: "NBFCs & AIFs Advised"    },
      { value: "6 Mos", label: "Avg. RBI Approval Timeline" },
      { value: "100%",  label: "Application Success Rate" },
      { value: "₹500 Cr+", label: "AIF Corpus Structured" },
    ],
    offerings: [
      { title: "NBFC Registration Advisory",   desc: "RBI NBFC registration process including net owned fund requirements, business plan, and policy documentation." },
      { title: "AIF Category I/II/III Launch",  desc: "SEBI AIF registration for venture capital, private equity, hedge fund, and real estate fund structures." },
      { title: "Investment Manager Setup",     desc: "Investment management company setup, SEBI registration, and compliance framework." },
      { title: "Fund Documentation",           desc: "PPM, contribution agreements, investment policy, and related fund document preparation." },
      { title: "Regulatory Compliance Setup",  desc: "Internal controls, ALM, NPA provisioning, and monthly/quarterly compliance reporting frameworks." },
      { title: "Capital Planning",             desc: "Optimal capital structure, leverage planning, and fundraising strategy for newly registered entities." },
      { title: "Technology & KYC Setup",       desc: "Coordination of CBS, loan management systems, and KYC infrastructure for new NBFCs." },
      { title: "Ongoing Regulatory Support",   desc: "Annual return filing, RBI/SEBI inspection support, and regulatory change management." },
    ],
    process: [
      { step: "01", title: "Feasibility & Business Plan",  desc: "Assess regulatory requirements, business viability, and net owned fund eligibility." },
      { step: "02", title: "Entity & Structure Setup",     desc: "Incorporate holding company, set up NOF, and prepare statutory documents." },
      { step: "03", title: "Application Preparation",      desc: "Prepare and file RBI/SEBI application with all required documents and disclosures." },
      { step: "04", title: "Regulatory Liaison",           desc: "Respond to RBI/SEBI queries and provide additional information as requested." },
      { step: "05", title: "License & Compliance Launch",  desc: "Receive license, set up compliance framework, and commence operations." },
    ],
    why: [
      { title: "Proven Track Record",   desc: "25+ successful NBFC and AIF launches with 100% application success rate." },
      { title: "Regulatory Expertise",  desc: "Deep knowledge of RBI Master Directions and SEBI AIF Regulations including latest amendments." },
      { title: "End-to-End Support",    desc: "From entity incorporation through post-launch compliance — a single advisor throughout." },
      { title: "Network Access",        desc: "Connections to RBI and SEBI advisors, legal counsel, and auditors for smooth regulatory navigation." },
    ],
    industries: ["Family Offices","Entrepreneurs","PE/VC Firms","Real Estate Funds","Microfinance","Consumer Finance"],
  },

  "msme-solutions": {
    slug: "msme-solutions", title: "MSME / SME Solutions", pill: "MSME Finance",
    color: GOLD, range: "₹10 L – ₹50 Cr",
    tagline: "Unlocking Capital for India's Small & Medium Enterprises.",
    heroDesc: "OMNI Fincon provides dedicated credit advisory and access to government-backed and institutional financing for MSMEs and SMEs — covering working capital, term loans, CGTMSE-backed credit, and supply chain finance.",
    stats: [
      { value: "₹500 Cr+", label: "MSME Credit Facilitated" },
      { value: "2,000+",    label: "MSME Clients Served"     },
      { value: "48 Hrs",    label: "Initial Sanction Target" },
      { value: "20+",       label: "MSME Lending Partners"   },
    ],
    offerings: [
      { title: "CGTMSE-Backed Loans",          desc: "Collateral-free loans for MSMEs under the Credit Guarantee Fund Trust for Micro and Small Enterprises." },
      { title: "Working Capital Finance",       desc: "CC/OD, invoice discounting, and bill discounting facilities to manage operational cash flow needs." },
      { title: "Equipment & Machinery Loan",   desc: "Term financing for plant, machinery, tools, and capital equipment with equipment security." },
      { title: "Supply Chain Finance",          desc: "Vendor and dealer financing programs linked to anchor corporate purchase orders." },
      { title: "Startup & New Enterprise Loan", desc: "Seed capital and early-stage credit advisory including Startup India and Mudra scheme access." },
      { title: "Export Finance",               desc: "Pre-shipment and post-shipment credit, LC discounting, and ECGC-backed export credit." },
      { title: "Cluster Finance Programs",     desc: "Industry-specific cluster finance programs for textile, garment, pharma, and agro-processing clusters." },
      { title: "OD Against Property",          desc: "Overdraft facilities against business property for flexible short-term capital access." },
    ],
    process: [
      { step: "01", title: "Business Assessment",          desc: "Understand business type, revenue, banking history, and specific capital requirement." },
      { step: "02", title: "Scheme Identification",        desc: "Map requirement to appropriate government scheme, institutional product, or bank offering." },
      { step: "03", title: "Documentation Preparation",    desc: "Collect, organise, and verify all required documentation for swift lender processing." },
      { step: "04", title: "Lender Submission",            desc: "Submit application to most appropriate lender from our 20+ MSME lending partners." },
      { step: "05", title: "Sanction & Disbursal Follow-Up", desc: "Track application status and coordinate any additional queries for fast disbursal." },
    ],
    why: [
      { title: "MSME-Focused Expertise",    desc: "Dedicated MSME credit advisory team with deep knowledge of all government schemes and bank products." },
      { title: "Government Scheme Access",  desc: "PMEGP, Mudra, Stand-Up India, CGTMSE — we ensure you access every eligible scheme." },
      { title: "Digital Processing",        desc: "Paperless documentation and digital submission for faster lender processing and approvals." },
      { title: "After-Loan Support",        desc: "Ongoing credit health monitoring, renewal advisory, and top-up loan guidance." },
    ],
    industries: ["Textile & Garment","Food Processing","Pharmaceutical","Auto Components","Construction Materials","Retail","Agriculture","IT & Software"],
  },

  "personal-loan": {
    slug: "personal-loan", title: "Personal Loan", pill: "Retail Banking",
    color: PURPLE, range: "₹50,000 – ₹50 Lakh",
    tagline: "Quick, Hassle-Free Personal Loans at Competitive Rates.",
    heroDesc: "OMNI Fincon's Personal Loan advisory service matches your profile to the best personal loan offer from 30+ banks and NBFCs — ensuring competitive rates, faster approval, and complete transparency.",
    stats: [
      { value: "₹200 Cr+", label: "Personal Loans Facilitated" },
      { value: "30+",       label: "Lending Partners"           },
      { value: "24 Hrs",    label: "Avg. Approval Time"         },
      { value: "10.5%",     label: "Best Rate Available"        },
    ],
    offerings: [
      { title: "Salaried Personal Loan",      desc: "Attractive rates for salaried professionals with competitive processing fees and flexible tenures up to 7 years." },
      { title: "Self-Employed Personal Loan", desc: "Personal loans for self-employed individuals based on ITR, banking, and GST turnover." },
      { title: "Professional Loan",           desc: "Specialized loans for doctors, CAs, architects, and other professionals with preferential pricing." },
      { title: "Balance Transfer",            desc: "Transfer existing personal loan to lower interest rate lender for significant interest savings." },
      { title: "Top-Up Loan",                 desc: "Additional loan amount on existing personal loan relationships at competitive rates." },
      { title: "Emergency Loan",              desc: "Quick-disbursal personal loans for urgent financial requirements within 24-48 hours." },
      { title: "Marriage Loan",               desc: "Purpose-specific personal loans for wedding expenses with competitive rates and flexible repayment." },
      { title: "Travel Loan",                 desc: "Quick loans for domestic and international travel with competitive interest rates." },
    ],
    process: [
      { step: "01", title: "Free Credit Assessment",    desc: "Check CIBIL score, calculate eligibility, and identify the best product for your profile." },
      { step: "02", title: "Product Matching",          desc: "Compare 30+ lenders for rate, processing fee, and disbursal timeline." },
      { step: "03", title: "Document Collection",       desc: "Minimal documentation — KYC, income proof, and bank statements." },
      { step: "04", title: "Application Submission",    desc: "Submit application to selected lender with complete documentation." },
      { step: "05", title: "Approval & Disbursal",      desc: "Track approval and coordinate swift disbursal directly to your account." },
    ],
    why: [
      { title: "Best Rate Guarantee",     desc: "We compare 30+ lenders to ensure you get the lowest possible interest rate for your profile." },
      { title: "Zero Cost Advisory",      desc: "Our personal loan advisory service is completely free for borrowers." },
      { title: "Paperless Process",       desc: "Digital KYC and instant verification for faster approvals without physical visits." },
      { title: "Dedicated Manager",       desc: "A dedicated loan manager tracks your case from application through disbursal." },
    ],
    industries: ["Salaried Employees","Self-Employed Professionals","Business Owners","Doctors & CAs","Government Employees"],
  },

  "business-loan": {
    slug: "business-loan", title: "Business Loan", pill: "Retail Banking",
    color: G, range: "₹5 Lakh – ₹10 Crore",
    tagline: "Fuel Your Business Growth with the Right Credit Solution.",
    heroDesc: "OMNI Fincon's Business Loan advisory service navigates 30+ lenders to secure the optimal credit facility — unsecured or secured — for your business expansion, working capital, or equipment investment needs.",
    stats: [
      { value: "₹400 Cr+", label: "Business Loans Facilitated" },
      { value: "3,000+",    label: "Business Clients Served"    },
      { value: "48 Hrs",    label: "Avg. Sanction Timeline"     },
      { value: "12.5%",     label: "Best Rate Available"        },
    ],
    offerings: [
      { title: "Unsecured Business Loan",   desc: "Collateral-free loans up to ₹2 Cr for established businesses based on turnover and banking track record." },
      { title: "Secured Business Loan",     desc: "Larger business credit facilities secured against property, equipment, or other assets." },
      { title: "Business Expansion Loan",   desc: "Capital for opening new branches, increasing capacity, or entering new markets." },
      { title: "Equipment Finance",         desc: "Asset-backed financing for machinery, commercial vehicles, and capital equipment." },
      { title: "Invoice Discounting",       desc: "Convert outstanding invoices from creditworthy buyers into immediate working capital." },
      { title: "GST-Based Loan",            desc: "Quick business loans based on GST turnover — no extensive documentation required." },
      { title: "Business Balance Transfer", desc: "Refinance existing high-cost business credit to lower interest rate facilities." },
      { title: "Overdraft Facility",        desc: "Flexible revolving credit facility against business turnover or property security." },
    ],
    process: [
      { step: "01", title: "Business Profile Assessment", desc: "Understand business vintage, turnover, banking history, and specific credit requirement." },
      { step: "02", title: "Eligibility Analysis",        desc: "Calculate eligibility across 30+ lenders based on income, banking, and credit profile." },
      { step: "03", title: "Optimal Product Selection",   desc: "Recommend best lender-product combination for maximum loan amount at minimum cost." },
      { step: "04", title: "Documentation & Application", desc: "Collect minimal required documents and submit complete application to lender." },
      { step: "05", title: "Sanction & Disbursal",        desc: "Coordinate sanction letter review and arrange swift disbursal of funds." },
    ],
    why: [
      { title: "Maximum Eligibility",    desc: "Our analysis maximises your loan eligibility across multiple lenders simultaneously." },
      { title: "Fastest Disbursal",      desc: "Pre-negotiated fast-track processes with lenders for sanction within 48 hours for eligible profiles." },
      { title: "Hidden Charge Free",     desc: "Complete disclosure of all fees, charges, and prepayment terms before you apply." },
      { title: "Ongoing Relationship",   desc: "We monitor your credit health and proactively advise on refinancing and top-up opportunities." },
    ],
    industries: ["Retail & Trading","Manufacturing","Services","Healthcare","Construction","Food & Beverage","Education","Logistics"],
  },

  "home-loan": {
    slug: "home-loan", title: "Home Loan", pill: "Retail Banking",
    color: BLUE, range: "₹20 Lakh – ₹10 Crore",
    tagline: "Making Home Ownership a Reality at the Best Rates.",
    heroDesc: "OMNI Fincon's Home Loan advisory guides you from property selection through loan disbursal — comparing rates from 25+ banks and HFCs to ensure you get the best deal on your dream home.",
    stats: [
      { value: "₹500 Cr+", label: "Home Loans Facilitated" },
      { value: "2,500+",    label: "Home Buyers Served"     },
      { value: "8.4%",      label: "Best Rate Available"    },
      { value: "25+",       label: "Lender Partners"        },
    ],
    offerings: [
      { title: "Home Purchase Loan",         desc: "Loans for purchase of ready-to-move, under-construction, or resale residential properties." },
      { title: "Home Construction Loan",     desc: "Plot purchase plus construction financing with stage-wise disbursals linked to construction progress." },
      { title: "Balance Transfer",           desc: "Migrate existing home loan to lower rate lender for substantial interest cost savings." },
      { title: "Top-Up Home Loan",           desc: "Additional loan against existing home loan for renovation, personal, or business purposes." },
      { title: "NRI Home Loan",              desc: "Home loans for non-resident Indians with FEMA-compliant structures and attractive rates." },
      { title: "Home Loan Tax Planning",     desc: "Optimise Section 80C and Section 24 tax benefits through smart loan structuring." },
      { title: "Affordable Housing Loan",    desc: "PMAY-linked affordable housing loans with subsidy benefit calculation and application." },
      { title: "Composite Loan",             desc: "Combined plot purchase and construction loan for ground-up residential development." },
    ],
    process: [
      { step: "01", title: "Eligibility & Budget Planning", desc: "Calculate maximum loan eligibility and advise on optimal property budget and EMI planning." },
      { step: "02", title: "Property Due Diligence",        desc: "Verify property title, approvals, and lender acceptability before application." },
      { step: "03", title: "Rate Comparison",               desc: "Compare processing fees, interest rates, and service quality across 25+ lenders." },
      { step: "04", title: "Documentation & Submission",    desc: "Prepare and submit complete application file with minimal errors for fast processing." },
      { step: "05", title: "Approval & Registration",       desc: "Coordinate lender approval, legal opinion, and property registration support." },
    ],
    why: [
      { title: "Rate Discovery",         desc: "Comprehensive comparison across 25+ banks and HFCs for the lowest rate on your profile." },
      { title: "Legal Coordination",     desc: "Coordination with empanelled lawyers for quick title opinion and registration support." },
      { title: "PMAY Subsidy Advisory",  desc: "We ensure all eligible clients apply for PMAY interest subsidy — saving up to ₹2.67 lakh." },
      { title: "Lifetime Support",       desc: "Ongoing support for balance transfer, top-up, and foreclosure throughout your loan tenure." },
    ],
    industries: ["Salaried Home Buyers","Self-Employed Professionals","NRI Buyers","First-Time Home Buyers","HNI Real Estate Investors"],
  },

  "loan-against-property": {
    slug: "loan-against-property", title: "Loan Against Property", pill: "Retail Banking",
    color: GOLD, range: "₹50 Lakh – ₹50 Crore",
    tagline: "Unlock Your Property's Value for Business & Personal Growth.",
    heroDesc: "OMNI Fincon structures optimal Loan Against Property solutions — maximising LTV, minimising rate, and ensuring swift processing for residential, commercial, and industrial property owners.",
    stats: [
      { value: "₹300 Cr+", label: "LAP Disbursals Facilitated" },
      { value: "500+",       label: "LAP Cases Processed"       },
      { value: "65%",        label: "Max LTV Achieved"          },
      { value: "9.5%",       label: "Best Rate Available"       },
    ],
    offerings: [
      { title: "Residential LAP",     desc: "Loans against owned residential property — apartment, villa, or independent house." },
      { title: "Commercial LAP",      desc: "Higher LTV loans against commercial office, shop, or warehouse property." },
      { title: "Industrial LAP",      desc: "Financing against factory, industrial plot, or manufacturing facility." },
      { title: "LAP for Business",    desc: "Business working capital, expansion, and debt consolidation through property-backed loans." },
      { title: "LAP Balance Transfer", desc: "Switch existing LAP to lower rate lender for reduced interest burden." },
      { title: "LAP Top-Up",          desc: "Additional loan against existing LAP relationship based on enhanced property value." },
      { title: "Rent Securitisation",  desc: "High-LTV loans against income-producing leased properties with committed rentals." },
      { title: "Multi-Property LAP",   desc: "Pooled loan against multiple properties for higher loan quantum and better terms." },
    ],
    process: [
      { step: "01", title: "Property Valuation Advisory", desc: "Independent market valuation estimate before approaching lenders to set expectations." },
      { step: "02", title: "LTV & Rate Comparison",       desc: "Compare maximum LTV and rates across 20+ lenders for best overall deal." },
      { step: "03", title: "Document Preparation",        desc: "Organise property documents, income proof, and legal clearances for lender submission." },
      { step: "04", title: "Application & Technical Valuation", desc: "Manage lender's technical valuation and legal opinion process." },
      { step: "05", title: "Sanction & Equitable Mortgage", desc: "Review sanction terms and coordinate equitable mortgage creation and disbursement." },
    ],
    why: [
      { title: "Maximum LTV",          desc: "Our lender relationships enable maximum loan-to-value up to 65% of property value." },
      { title: "Faster Processing",    desc: "Streamlined valuation and legal opinion process through our empanelled network." },
      { title: "Lower Rate",           desc: "LAP rates from 9.5% — significantly lower than unsecured business or personal loans." },
      { title: "No Prepayment Penalty", desc: "We negotiate prepayment-free structures allowing early loan closure without cost." },
    ],
    industries: ["Business Owners","Self-Employed Professionals","Real Estate Investors","Corporates","Property Owners"],
  },

  "working-capital-loan": {
    slug: "working-capital-loan", title: "Working Capital Loan", pill: "Retail Banking",
    color: G, range: "₹25 Lakh – ₹25 Crore",
    tagline: "Keep Your Business Moving with the Right Working Capital Solution.",
    heroDesc: "OMNI Fincon structures optimal working capital credit facilities for businesses — from cash credit and overdraft to invoice discounting and bill discounting — ensuring you never face a liquidity crunch.",
    stats: [
      { value: "₹600 Cr+", label: "Working Capital Arranged" },
      { value: "1,500+",    label: "Business Clients Served" },
      { value: "7 Days",    label: "Avg. CC Renewal Timeline" },
      { value: "25+",       label: "Lender Partners"          },
    ],
    offerings: [
      { title: "Cash Credit (CC) Facility", desc: "Revolving credit against stock, debtors, and receivables with flexible drawdown and repayment." },
      { title: "Overdraft (OD) Facility",   desc: "Business current account overdraft against property, FDs, or insurance policies." },
      { title: "Invoice Discounting",       desc: "Immediate liquidity against verified invoices from creditworthy buyers — confidential or notified." },
      { title: "Bill Discounting",          desc: "Bills of exchange discounting for domestic and export transactions." },
      { title: "Letter of Credit (LC)",     desc: "Domestic and international LC facility for domestic purchase and import transactions." },
      { title: "Bank Guarantee (BG)",       desc: "Performance, financial, and advance bank guarantees for government and PSU contracts." },
      { title: "Supply Chain Finance",      desc: "Structured programs for vendors and dealers of large anchor corporates." },
      { title: "WCDL (Working Capital Demand Loan)", desc: "Term-loan variant of working capital for businesses with cyclical cash flow needs." },
    ],
    process: [
      { step: "01", title: "Working Capital Assessment", desc: "Analyse business cycle, inventory holding, debtor collection, and current credit utilisation." },
      { step: "02", title: "Facility Design",            desc: "Recommend optimal mix of CC, OD, LC, BG, and invoice discounting based on business model." },
      { step: "03", title: "Lender Selection",           desc: "Identify most appropriate bank or NBFC offering best rate and turnaround for the required facility." },
      { step: "04", title: "Documentation & Submission", desc: "Prepare audited statements, CMA data, and stock statements for lender appraisal." },
      { step: "05", title: "Sanction & Annual Renewal",  desc: "Coordinate sanction and provide annual renewal support for continued working capital access." },
    ],
    why: [
      { title: "Full Facility Suite",     desc: "Access to every working capital instrument from CC/OD to LC/BG through one relationship." },
      { title: "Optimal Pricing",         desc: "Competitive tendering across 25+ lenders for best rate on working capital facilities." },
      { title: "Fast Renewal",            desc: "Pre-prepared renewal documentation ensures zero downtime in working capital access." },
      { title: "Technology Integration",  desc: "Digital invoice discounting platforms for real-time working capital access at lowest cost." },
    ],
    industries: ["Manufacturing","Trading","Export-Import","Healthcare","Retail","Construction","Food & Beverages","Textile"],
  },
};
